version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2022.03
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: linux
    parallelism: 5
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Demonstrate that Mongo DB is available as localhost
          command: |
            for i in $(seq 1 5); do docker-compose up -d && s=0 && break || s=$? && sleep 10; done; (continue $s)
            for i in $(seq 1 5); do checkout && s=0 && break || s=$? && sleep 10; done; (continue $s)
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run : |
               chmod +x fit-up.sh
workflows:
  all-test:
    jobs:
      - test:
          name: "test-10.9.0"
          node-version: 10.9.0
      - test:
          name: "test-11.9.0"
          node-version: 11.9.0
      - test:
          name: "test-12.9.0"
          node-version: 12.9.0
      - test:
          name: "test-13.9.0"
          node-version: 13.9.0
      - test:
          name: "test-13.10.0"
          node-version: 13.10.0
